source 'https://rubygems.org'

gem 'puma'
gem 'rack'
gem 'webmachine'
gem 'webmachine-linking', github: 'Asmod4n/webmachine-linking'

gem 'jwt'
gem 'sequel'
gem 'sqlite3'

gem 'tilt-jbuilder'

group :development, :test do
  gem 'byebug'

  gem 'reek'
  gem 'rubocop'

  gem 'cucumber'
  gem 'database_cleaner'
  gem 'rack-test'
  gem 'rspec'

  gem 'simplecov', require: false
end
